apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: front-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-angular
  template:
    metadata:
      labels:
        app: front-angular
    spec:
      containers:
        - name: spring-container
          image: caraz0/front-angular:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: angular-port
              protocol: TCP


---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: front-angular
spec:
  type: NodePort
  selector:
    app: front-angular
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30200
